// frontend/src/components/_Layout/Footer.vue
<template>
  <div id="footer-body">
    <div class="item-slot en-font">{{ FOOTER_TEXT }}</div>
    <div class="item-slot">
      <a target="blank" href="https://ko-fi.com/sseries">
        <img class="footer-icon" alt="kofi" src="/kofi.png" />
      </a>
      <a target="blank" href="https://github.com/S-Series">
        <img class="footer-icon" alt="github" src="/github.png" />
      </a>
      <a target="blank" href="https://github.com/S-Series">
        <img class="footer-icon" alt="sseries" src="/sseries.png" />
      </a>
    </div>
  </div>
</template>

<script setup lang="ts">
import "@/components/_Layout/Footer.css";
const FOOTER_TEXT = `Contact: SSeries000923@gmail.com\nWuthering Waves and all related assets are © Kuro Games.\nThis website is an unofficial fan project and is not affiliated with Kuro Games.`;
</script>

// frontend/src/components/Footer.tsx
import { useAppStore } from "@/hooks/appStore";
import "./Footer.css";

export default function Footer() {

    //const { lang, setLang } = useAppStore();

    return (
        <div id="footer-body">
            <div className="item-slot en-font">
                {
                    `All assets © Kuro Games 2024 || non-official fan project
                    E-mail: SSeries000923@gmail.com || Discord: SSeries0923`
                }
            </div>
            <div className="item-slot">
                <a href="#">
                    <img className="footer-icon"
                        alt="title"
                        src="/kofi.png" />
                </a>
                <a href="#">
                    <img className="footer-icon"
                        alt="title"
                        src="/github.png" />
                </a>
                <a href="#">
                    <img className="footer-icon"
                        alt="title"
                        src="/sseries.png" />
                </a>
            </div>
        </div>
    )
}
