// frontend/src/components/_Layout/Footer.vue
<template>
  <div id="footer-body">
    <div class="item-slot en-font">{{ FOOTER_TEXT }}</div>
    <div class="item-slot">
      <a target="blank" href="https://ko-fi.com/sseries">
        <img class="footer-icon" alt="kofi" src="/kofi.png" />
      </a>
      <a target="blank" href="https://github.com/S-Series">
        <img class="footer-icon" alt="github" src="/github.png" />
      </a>
      <a target="blank" href="https://github.com/S-Series">
        <img class="footer-icon" alt="sseries" src="/sseries.png" />
      </a>
    </div>
  </div>
</template>

<script setup lang="ts">
import "@/components/_Layout/Footer.css";
const FOOTER_TEXT = `Contact: SSeries000923@gmail.com\nWuthering Waves and all related assets are © Kuro Games.\nThis website is an unofficial fan project and is not affiliated with Kuro Games.`;
</script>

// frontend/src/components/_Layout/Footer.tsx
import "@/components/_Layout/Footer.css"

const FOOTER_TEXT = `Contact: SSeries000923@gmail.com\nWuthering Waves and all related assets are © Kuro Games.\nThis website is an unofficial fan project and is not affiliated with Kuro Games.`

export default function Footer() {

    return (
        <div id="footer-body">
            <div className="item-slot en-font">{FOOTER_TEXT}</div>
            <div className="item-slot">
                <a target="blank" href="https://ko-fi.com/sseries">
                    <img className="footer-icon"
                        alt="title"
                        src="/kofi.png" />
                </a>
                <a target="blank" href="https://github.com/S-Series">
                    <img className="footer-icon"
                        alt="title"
                        src="/github.png" />
                </a>
                <a target="blank" href="https://github.com/S-Series">
                    <img className="footer-icon"
                        alt="title"
                        src="/sseries.png" />
                </a>
            </div>
        </div>
    )
}
