// frontend/src/components/_Layout/Layout.tsx
import { Outlet, useLocation } from "react-router-dom";
import { useEffect } from "react";

import Navbar from "@/components/_Layout/Navbar";
import Footer from "@/components/_Layout/Footer";

import "@/components/_Layout/Layout.css";

export default function Layout() {
  const location = useLocation();

  useEffect(() => {
    document.body.classList.remove(
      "page-home",
      "page-characters",
      "page-card"
    );

    switch (location.pathname) {
      case "/":
        document.body.classList.add("page-home");
        break;

      case "/characters":
        document.body.classList.add("page-characters");
        break;

      case "/card":
        document.body.classList.add("page-card");
        break;
    }

    return () => {
      document.body.classList.remove(
        "page-home",
        "page-characters",
        "page-card"
      );
    };
  }, [location.pathname]);

  return (
    <>
      <header>
        <Navbar />
      </header>

      <main id="main-container">
        <Outlet />
      </main>

      <footer>
        <Footer />
      </footer>
    </>
  );
}

// frontend/src/components/_Layout/Layout.vue
<template>
  <header>
    <Navbar />
  </header>
  <main id="main-container">
    <RouterView />
  </main>
  <footer>
    <Footer />
  </footer>
</template>

<script setup lang="ts">
import { watch } from "vue";
import { useRoute } from "vue-router";
import Navbar from "@/components/_Layout/Navbar.vue";
import Footer from "@/components/_Layout/Footer.vue";
import "@/components/_Layout/Layout.css";
import "@/pages/_Page.css";

const route = useRoute();

const PAGE_CLASSES = ["page-home", "page-characters", "page-card", "page-profile"];
const PATH_MAP: Record<string, string> = {
  "/": "page-home",
  "/characters": "page-characters",
  "/card": "page-card",
  "/profile": "page-profile",
};

watch(
  () => route.path,
  (path) => {
    document.body.classList.remove(...PAGE_CLASSES);
    const cls = PATH_MAP[path];
    if (cls) document.body.classList.add(cls);
  },
  { immediate: true }
);
</script>
