// frontend/src/components/features/Card/EchoDragSelect.vue
<template>
  <div class="echo-drag-select">
    <div class="echo-drag-list">
      <draggable
        v-model="items"
        item-key="id"
        handle=".echo-drag-item"
        animation="150"
        @end="onDragEnd"
      >
        <template #item="{ element, index }">
          <div
            :class="[
              'echo-drag-item',
              index === 0 ? 'main' : '',
              num === element.id ? 'activated' : '',
              index < 5 ? 'selected' : '',
              element.echoName === null ? 'disable' : '',
            ].filter(Boolean).join(' ')"
            @click="handleClick(element.id)"
          >
            <div class="hover-motion">
              <img class="echo-img"
                :src="`/ico/echos/${element.src[0]}`"
                @error="(e) => { (e.currentTarget as HTMLImageElement).src = '/default.webp' }"
              />
              <span class="echo-drag-label">{{ element.echoName }}</span>
              <img class="score-img" :src="`/ico/rank/${element.src[1]}`" />
            </div>
          </div>
        </template>
      </draggable>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import draggable from "vuedraggable";
import { useCharacterStore } from "@/stores/characterDataStore";
import { useAppStore, type LangType } from "@/stores/appStore";
import { ECHO_CANDIDATES } from "@/datas/echos";
import { setEchoDataIndexes } from "@/runtime/characterData.helpers";
import { getEquipmentRank } from "@/types/character.type";
import type { EchoRuntime } from "@/runtime/echo.runtime";
import "./EchoDragSelect.css";

type EchoIndexTuple = [number, number, number, number, number, number, number, number, number, number];

defineProps<{ num: number }>();
const emit = defineEmits<{ click: [id: number] }>();

const charStore = useCharacterStore();
const appStore = useAppStore();

type DragItem = {
  id: number;
  echoName: string | null;
  src: [string, string];
};

function buildItems(
  echoData: EchoRuntime[] | null,
  echoDataIndex: number[],
  lang: LangType
): DragItem[] {
  const names = ECHO_CANDIDATES[lang];
  const base = Array.from({ length: 10 }, (_, i): DragItem => ({
    id: i,
    echoName: names.find((n) => n.echoId === echoData?.[i]?.echoId)?.text ?? null,
    src: [
      `${echoData?.[i]?.echoId ?? ""}.webp`,
      `${getEquipmentRank(charStore.equipmentScore?.[i][1] ?? 0)}.png`,
    ],
  }));
  return echoDataIndex.map((id) => base.find((v) => v.id === id)!);
}

const items = ref<DragItem[]>(
  buildItems(charStore.characterData.echoData, charStore.characterData.echoDataIndex, appStore.lang)
);

watch(
  [
    () => charStore.characterData.echoData,
    () => charStore.characterData.echoDataIndex,
    () => appStore.lang,
    () => charStore.equipmentScore,
  ],
  () => {
    items.value = buildItems(
      charStore.characterData.echoData,
      charStore.characterData.echoDataIndex,
      appStore.lang
    );
  },
  { deep: true }
);

function onDragEnd() {
  const nextIndexes = items.value.map((item) => item.id);
  if (nextIndexes.length !== 10) return;
  charStore.patchCharacterData(
    setEchoDataIndexes(charStore.characterData, nextIndexes as EchoIndexTuple)
  );
}

function handleClick(id: number) {
  emit("click", id);
}
</script>

// frontend/src/components/features/Card/EchoDragSelect.tsx
import React, { useEffect, useState } from "react";
import {
	DndContext,
	closestCenter,
	PointerSensor,
	useSensor,
	useSensors,
	type DragEndEvent,
} from "@dnd-kit/core";
import {
	SortableContext,
	useSortable,
	verticalListSortingStrategy,
	arrayMove,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";

import "./EchoDragSelect.css";
import { useCharacter } from "@/stores/characterDataStore";
import type { EchoRuntime } from "@/runtime/echo.runtime";
import { ECHO_CANDIDATES } from "@/datas/echos";
import { useAppStore, type LangType } from "@/stores/appStore";
import { setEchoDataIndexes } from "@/runtime/characterData.helpers";
import { getEquipmentRank } from "@/types/character.type";

type DragItem = {
	id: number;
	num: number;
	echoName: string | null;
	src: string[];
	label: EchoRuntime | null;
};

const createItems = (num: number, data: EchoRuntime[] | null, scores: any, lang: LangType): DragItem[] => {
	const names = ECHO_CANDIDATES[lang];

	return Array.from({ length: 10 }, (_, index) => ({
		id: index,
		num: num,
		echoName: names.find(item => item.echoId === data?.[index].echoId)?.text ?? null,
		src: [`${data?.[index].echoId}.webp`, `${getEquipmentRank(scores?.[Math.abs(index)][1] ?? 0)}.png`],
		label: null,
	}));
};

const reOrderItems = (order: number[], items: DragItem[]) => {
	return order.map(id => items.find(v => v.id === id)!)
}

type SortableItemProps = {
	baseUrl: string;
	num: number;
	item: DragItem;
	index: number;
	onClick?: React.Dispatch<React.SetStateAction<0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9>>;
};

type EchoIndexTuple =
	[number, number, number, number, number,
		number, number, number, number, number];

function assertEchoIndexTuple(arr: number[]): asserts arr is EchoIndexTuple {
	if (arr.length !== 10) {
		throw new Error("Echo index must have length 10");
	}
}

function SortableItem({ item, baseUrl, index, onClick }: SortableItemProps) {
	const {
		attributes,
		listeners,
		setNodeRef,
		transform,
		transition,
		isDragging,
	} = useSortable({ id: item.id });

	const style: React.CSSProperties = {
		transform: CSS.Transform.toString(transform),
		transition,
	};

	const isSelected = index < 5;
	const isActivated = (item.num === index);

	return (
		<div
			ref={setNodeRef}
			style={style}
			className={[
				"echo-drag-item",
				index === 0 ? "main" : "",
				isDragging ? "dragging" : "",
				isActivated ? "activated" : "",
				isSelected ? "selected" : "",
				item.echoName === null ? "disable" : ""
			].join(" ").trim()}
			onClick={() => { if (onClick) onClick(item.id as 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9); }}
			{...attributes}
			{...listeners}
		>
			<div className="hover-motion">
				<img className="echo-img" src={`${baseUrl}/ico/echos/${item.src[0]}`} 
					onError={(e) => {
						e.currentTarget.onerror = null;
						e.currentTarget.src = "/default.webp"
					}}/>
				<span className="echo-drag-label">{item.echoName}</span>
				<img className="score-img" src={`/ico/rank/${item.src[1]}`} />
			</div>
		</div>
	);
}

type Props = {
	num: number;
	onClick?: React.Dispatch<React.SetStateAction<0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9>>;
}

export default function EchoDragSelect({num, onClick}: Props) {
	const { lang } = useAppStore();
	const { characterData, equipmentScore, patchCharacterData } = useCharacter();
	const [items, setItems] = useState<DragItem[]>(createItems(num, null, equipmentScore, lang));
	const BASE_URL = import.meta.env.VITE_IMAGE_BASE;

	useEffect(() => {
		setItems(
			reOrderItems(
				characterData.echoDataIndex,
				createItems(num, characterData.echoData, equipmentScore, lang)
			)
		);
	}, [num, characterData.echoData, characterData.echoDataIndex, lang, equipmentScore]);

	const patchEchoDataIndexes = (nextIndexes: number[]) => {
		assertEchoIndexTuple(nextIndexes);

		patchCharacterData(
			setEchoDataIndexes(characterData, nextIndexes)
		);
	};

	const sensors = useSensors(
		useSensor(PointerSensor, {
			activationConstraint: {
				distance: 6,
			},
		})
	);

	const handleDragEnd = (event: DragEndEvent) => {
		const { active, over } = event;

		if (!over || active.id === over.id) return;

		const oldIndex = items.findIndex((item) => item.id === active.id);
		const newIndex = items.findIndex((item) => item.id === over.id);

		const nextItems = arrayMove(items, oldIndex, newIndex);
		const nextIndexes = nextItems.map((item) => item.id);

		setItems(nextItems);
		patchEchoDataIndexes(nextIndexes);
	};

	return (
		<div className="echo-drag-select">
			<DndContext
				sensors={sensors}
				collisionDetection={closestCenter}
				onDragEnd={handleDragEnd}
			>
				<SortableContext
					items={items.map((item) => item.id)}
					strategy={verticalListSortingStrategy}
				>
					<div className="echo-drag-list">
						{items.map((item, index) => (
							<SortableItem key={item.id} num={num} baseUrl={BASE_URL} item={item} index={item.id} onClick={onClick} />
						))}
					</div>
				</SortableContext>
			</DndContext>
		</div>
	);
}
