// frontend/src/components/features/Card/OcrDragSelectItem.tsx
import Select, { type SingleValue, type StylesConfig } from "react-select";
import { CSS } from "@dnd-kit/utilities";
import { useSortable } from "@dnd-kit/sortable";
import type { SelectOpt, SelectOptionStatOriginal } from "./EchoSelect.type";
import type { StatId } from "@/datas/stats";
import type React from "react";
import type { EchoRuntime } from "@/runtime/echo.runtime";
import { useEffect } from "react";
import type { DragItem } from "./OcrDragSelect";

type SortableItemProps = {
  item: {
    id: number;
    statId: StatId;
    statValue: number;
    statName: string | null;
  };
  index: number;
  styles: [StylesConfig<any,false>, StylesConfig<any,false>];
  options: [SelectOptionStatOriginal[], SelectOpt[]];
  onSelectChange: React.Dispatch<React.SetStateAction<DragItem[]>>;
};

//$ =================================================
export function OcrDragSelectItem({
  item,
  index,
  options,
  styles,
  onSelectChange,
}: SortableItemProps) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: item.id });

  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  const isSelected = index < 5;

  return (
    <div
      ref={setNodeRef}
      style={style}
      className={[
        "stat-drag-item",
        isDragging ? "dragging" : "",
        isSelected ? "selected" : "",
        item.statName === null ? "disable" : "",
      ].join(" ").trim()}
    >
      <div className="hover-motion">
        <button
          type="button"
          className="drag-handle"
          {...attributes}
          {...listeners}
        >
          ☰
        </button>

        <div
          className="stat-select-wrap"
          onPointerDown={(e) => e.stopPropagation()}
          onMouseDown={(e) => e.stopPropagation()}
        >
          <Select
            styles={styles[0]}
            options={options[0]}
            onChange={(opt) => {
              onSelectChange((prev) => {
                const next = [...prev];
                next[index] = {
                  ...prev[index],
                  statId: opt.value
                };
                return next;
              })
            }}
            menuPortalTarget={document.body}
            menuPosition="fixed"
            isSearchable={false}
            value={options[0].find((opt) => { return opt.value === item?.statId })}
          />
        </div>

        <div style={{width: "2.5%"}}/>

        <div
          className="stat-select-wrap"
          onPointerDown={(e) => e.stopPropagation()}
          onMouseDown={(e) => e.stopPropagation()}
        >
          <Select
            styles={styles[1]}
            options={options[1]}
            onChange={(opt) => {
              console.log(opt);
              onSelectChange((prev) => {
                const next = [...prev];
                next[index] = {
                  ...prev[index],
                  statValue: opt.value
                };
                return next;
              })
            }}
            menuPortalTarget={document.body}
            menuPosition="fixed"
            isSearchable={false}
            value={options[1].find((opt) => opt.value.toString() === item?.statValue?.toString())}
          />
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/features/Card/OcrDragSelectItem.vue
<template>
  <div
    :class="[
      'stat-drag-item',
      isDragging ? 'dragging' : '',
      isSelected ? 'selected' : '',
      item.statName === null ? 'disable' : '',
    ].filter(Boolean).join(' ')"
  >
    <div class="hover-motion">
      <button
        type="button"
        class="drag-handle"
      >
        ☰
      </button>

      <div class="stat-select-wrap">
        <select 
          :value="item.statId" 
          @change="updateStatId($event)"
          class="native-select wide"
        >
          <option 
            v-for="opt in options[0]" 
            :key="opt.value" 
            :value="opt.value"
          >
            {{ opt.label }}
          </option>
        </select>
      </div>

      <div style="width: 2.5%"/>

      <div class="stat-select-wrap">
        <select 
          :value="item.statValue" 
          @change="updateStatValue($event)"
          class="native-select"
        >
          <option 
            v-for="opt in options[1]" 
            :key="opt.value" 
            :value="opt.value"
          >
            {{ opt.label }}
          </option>
        </select>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { StatId } from '@/datas/stats';
import type { SelectOpt, SelectOptionStatOriginal } from './EchoSelect.type';

const props = defineProps<{
  item: {
    id: number;
    statId: StatId;
    statValue: number;
    statName: string | null;
  };
  index: number;
  options: [SelectOptionStatOriginal[], SelectOpt[]];
  isDragging?: boolean;
}>();

const emit = defineEmits<{
  'update:statId': [id: StatId];
  'update:statValue': [value: number];
}>();

const isSelected = computed(() => props.index < 5);

function updateStatId(event: Event) {
  const val = (event.target as HTMLSelectElement).value as StatId;
  emit('update:statId', val);
}

function updateStatValue(event: Event) {
  const val = parseFloat((event.target as HTMLSelectElement).value);
  emit('update:statValue', val);
}
</script>

<style scoped>
.native-select {
  width: 100%;
  background: #252525;
  color: white;
  border: 1px solid #444;
  border-radius: 4px;
  padding: 2px 4px;
  font-size: min(1vw, 0.8rem);
  appearance: none;
}
.native-select.wide {
  font-size: min(0.9vw, 0.75rem);
}
.drag-handle {
  cursor: grab;
  background: none;
  border: none;
  color: #888;
  font-size: 1.2rem;
  padding: 0 4px;
}
</style>
