// frontend/src/components/features/Card/OcrSelect.vue
<template>
  <div class="ocr-select-body">
    <div class="select-item-slot">
      <span class="item-slot-title"> Reorder Echoes </span>
      <div class="item-slot-container">
        <EchoDragSelect :num="selectIdx" @click="(id: number) => emit('update:selectIdx', id)" />
      </div>
    </div>

    <div class="select-item-slot">
      <span class="item-slot-title"> Edit Selected </span>
      <div class="item-slot-container">
        <EchoSelect :index="selectIdx" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import EchoSelect from './EchoSelect.vue';
import EchoDragSelect from './EchoDragSelect.vue';
import './OcrSelect.css';

defineProps<{
  selectIdx: number;
}>();

const emit = defineEmits<{
  'update:selectIdx': [id: number];
}>();
</script>

// frontend/src/components/features/Card/OcrSelect.tsx
import { useState } from "react";

import EchoSelect from "./EchoSelect";
import EchoDragSelect from "./EchoDragSelect";

import "./OcrSelect.css"

type EchoIndex = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

type Props = {
	selectIdx: EchoIndex;
	setSelectIdx: React.Dispatch<React.SetStateAction<EchoIndex>>;
}
export default function OcrSelect({selectIdx, setSelectIdx}: Props) {

	return (
		<div className="ocr-select-body">
			<div className="select-item-slot">
				<span className="item-slot-title"> asdf </span>

				<div className="item-slot-container">
					<EchoDragSelect num={selectIdx} onClick={setSelectIdx} />
				</div>
			</div>

			<div className="select-item-slot">
				<span className="item-slot-title"> asdf </span>

				<div className="item-slot-container">
					<EchoSelect index={selectIdx as EchoIndex} />
				</div>
			</div>
		</div>
	)
}
