// frontend/src/components/features/Card/StatSlot.tsx
import { useAppStore } from "@/stores/appStore";
import { FixedStats, type StatId } from "@/datas/stats";
import "./StatSlot.css"

interface StatSlotProps {
    statId: StatId;
    statValue: number;
    plusValue: number;
}

export default function StatSlot({ statId, statValue, plusValue }: StatSlotProps) {
    const { lang } = useAppStore();
    const isPct = ((
        statId.includes("crit")
        || statId.includes("Bns")
        || statId.includes("Pct"))
        ? true : false
    );
    
    return (
        <div className="stat-slot-body">
            <div className="container">
                <img src={`/ico/stats/${statId}.webp`}/>
                <span className={`${lang}-font`}>{
                    FixedStats[statId][lang]
                        .replace("アップ", " ✢")
                        .replace("加成", " ✢")
                }</span>
                <p className={`num-font ${isPct ? "" : "blank"}`}>
                    {isPct ? (statValue.toFixed(1) + "%") : statValue}
                </p>
            </div>
            <em className={`num-font`}>
                +{isPct ? (plusValue.toFixed(1) + "%") : plusValue}
            </em>
        </div>
    )
}

// frontend/src/components/features/Card/StatSlot.vue
<template>
  <div class="stat-slot-body">
    <div class="container">
      <img :src="`/ico/stats/${statId}.webp`" />
      <span :class="`${appStore.lang}-font`">{{ label }}</span>
      <p :class="`num-font ${isPct ? '' : 'blank'}`">
        {{ isPct ? statValue.toFixed(1) + "%" : statValue }}
      </p>
    </div>
    <em class="num-font">+{{ isPct ? plusValue.toFixed(1) + "%" : plusValue }}</em>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useAppStore } from "@/stores/appStore";
import { FixedStats, type StatId } from "@/datas/stats";
import "./StatSlot.css";

const props = defineProps<{ statId: StatId; statValue: number; plusValue: number }>();
const appStore = useAppStore();

const isPct = computed(() =>
  props.statId.includes("crit") || props.statId.includes("Bns") || props.statId.includes("Pct")
);

const label = computed(() =>
  FixedStats[props.statId][appStore.lang]
    .replace("アップ", " ✢")
    .replace("加成", " ✢")
);
</script>
