// frontend/src/pages/Profile.vue
<template>
  <div id="page-slot">
    <div v-if="authStore.isLoading" style="align-self: center">Loading...</div>

    <div v-else-if="authStore.user" class="profile-field">
      <img class="main-stand-image" :src="userImageUrl[2]" />
      <div class="container">
        <div class="user-info">
          <div class="profile-image-wrap">
            <img class="profile-image" :src="userImageUrl[0]" />
          </div>
          <div class="profile-image-wrap">
            <img class="profile-image" :src="userImageUrl[1]" />
          </div>
          <div class="text-box">
            <span class="num-font">{{ `Lv.${authStore.gameProfile?.gameLevel ?? 1}` }} <em>{{ authStore.user.nickname }}</em></span>
            <span class="num-font">{{ `${authStore.gameProfile?.server ?? 'unknown'} / Uid.` }} <em>{{ authStore.gameProfile?.gameUid ?? '- - - - - - -' }}</em></span>
            <span class="num-font">Joined. <em>{{ new Date(authStore.user.createdAt).toISOString().slice(0, 10) }}</em> ~</span>
          </div>
          <div class="button-box">
            <button>정보수정</button>
            <button @click="authStore.logoutAction()">로그아웃</button>
          </div>
        </div>
        <div class="game-info"></div>
      </div>
    </div>

    <div v-else class="login-field">
      <span>Login</span>
      <input class="input-field id" disabled type="email" placeholder="example@domain.com" v-model="email" />
      <input class="input-field password" disabled type="password" placeholder="password" v-model="password" />
      <button class="login-button normal" disabled @click="doLogin">
        <img src="/default.webp" />
        <span :class="`${appStore.lang}-font`">일반 계정으로 로그인</span>
      </button>
      <button class="login-button google" @click="authStore.loginWithGoogleAction()">
        <img src="/google.png" />
        <span :class="`${appStore.lang}-font`">Google 계정으로 로그인</span>
      </button>
      <button class="login-button signup" disabled>
        <img src="/default.webp" />
        <span :class="`${appStore.lang}-font`">회원가입</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import { useAppStore } from "@/stores/appStore";
import { useAuthStore } from "@/stores/authStore";
import "./Profile.css";

const appStore = useAppStore();
const authStore = useAuthStore();
const email = ref("");
const password = ref("");


const userImageUrl = computed(() => [
  authStore.user?.imageUrl ?? "/default.webp",
  `/character/${authStore.gameProfile?.characterId ?? "rover_spectro"}/ico.webp`,
  `/character/${authStore.gameProfile?.characterId ?? "rover_spectro"}/stand.png`,
]);

async function doLogin() {
  if (!email.value || !password.value) return;
  await authStore.loginAction(email.value, password.value);
}
</script>

// frontend/src/pages/Profile.tsx
import { useEffect, useMemo, useState } from "react";
import { type UserProfile } from "@/firebase/auth";

import { useAppStore } from "@/stores/appStore";
import { useAuthStore } from "@/stores/authStore";

import "./Profile.css"
import { saveGameProfile } from "@/firebase/user";

export default function Profile() {
  const { lang } = useAppStore();
  const { user, gameProfile, isLoading, signupAction, loginAction, loginWithGoogleAction, logoutAction } = useAuthStore();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const [isSignIn, setSignIn] = useState(false);

  const BASE_URL = import.meta.env.VITE_IMAGE_BASE;

  const userImageUrl = useMemo(() => {
    return [
      user?.imageUrl ?? "/default.webp",
      `${BASE_URL}/character/${gameProfile?.characterId ?? "rover_spectro"}/ico.webp`,
      `${BASE_URL}/character/${gameProfile?.characterId ?? "rover_spectro"}/stand.png`,
      `./stand.png`
    ]
  }, [user?.imageUrl, gameProfile?.characterId])

  if (isLoading) return <div style={{alignSelf: "center"}}>Loading...</div>
  return (
    <div id="page-slot">
      {user ? (
        <div className="profile-field">
          <img className="main-stand-image" src={userImageUrl[2]} />
          <div className="container">
            <div className="user-info">
              <div className="profile-image-wrap">
                <img className="profile-image" src={userImageUrl[0]} />
              </div>

              <div className="profile-image-wrap">
                <img className="profile-image" src={userImageUrl[1]} />
              </div>

              <div className="text-box">
                <span className="num-font">{`Lv.${gameProfile?.gameLevel ?? 1}`}  <em>{`${user.nickname}`}</em></span>
                <span className="num-font">{`${gameProfile?.server ?? "unknown"} / Uid.`} <em>{`${gameProfile?.gameUid ?? "- - - - - - -"}`}</em></span>
                <span className="num-font">Joined. <em>{`${new Date(user.createdAt).toISOString().slice(0, 10)}`}</em> ~</span>
                <span className="num-font">Membership. 
                  {"  "}{<img src="./default.webp"/>}{"  "}
                  (~<em>{`${new Date(user.createdAt).toISOString().slice(0, 10)}`})</em>
                </span>
              </div>
              <div className="button-box">
                <button>정보수정</button>
                <button onClick={() => logoutAction()}>로그아웃</button>
              </div>
            </div>

            <div className="game-info">
              
            </div>
          </div>
        </div>
      ) : (
        <div className="login-field">
          <span>Login</span>

          <input className="input-field id"
            disabled={true}
            type="email"
            placeholder="example@domain.com"
            onChange={(e) => setEmail(e.target.value)} />

          <input className="input-field password"
            disabled={true}
            type="password"
            placeholder="password"
            onChange={(e) => setPassword(e.target.value)} />

          <button className="login-button normal"
            disabled={true}
            onClick={() => { if (!email || !password) return; loginAction(email, password) }}>
            <img src="/default.webp" />
            <span className={`${lang}-font`}>일반 계정으로 로그인</span>
          </button>

          <button className="login-button google"
            disabled={false}
            onClick={() => loginWithGoogleAction()}>
            <img src="/google.png" />
            <span className={`${lang}-font`}>Google 계정으로 로그인</span>
          </button>

          <button className="login-button signup"
            disabled={true}
            onClick={() => { }}>
            <img src="/default.webp" />
            <span className={`${lang}-font`}>회원가입</span>
          </button>
        </div>
      )}
    </div>
  )
}
